### ISSUE TITLE
Slight problem with your solution to Problem 3

### ISSUE THREAD

**Issue by fission-mailed** [gk7huki/project-euler#1]
Hi, I found your solutions to the Euler Project problems that you submitted to the Odin Project. I wanted to check my answer with someone else and you were the first person in the list that had completed problem 3. 

First of all, your code does actaully give the correct solution (6857) to the problem of the case where n=600851475143, however your code wouldn't give the correct solution for every other n. For example if you set n = 27, your code would log the value 9 to the console, but 9 is not a prime number.

I know this probably sounds super nitpicky but as someone who would submit their code to the Odin Project, you no doubt take pride in your work and so just think of this as a friendly tip from a fellow coder and problem solver.

Good day.

**Comment by gk7huki** [comment]
Hi, good catch. Yes, there seems to be something wrong with the code. In fact, the check for divisibility (the `n%i === 0` test) should be run repeatedly until it fails, but in the current code it's run once and we move on to the next value. Changing the `if` to a `while` loop should fix the problem.

Cheers.
